### PR TITLE
refactor: adapt content and catalogue layout

### LINKED ISSUE #67: Make content align center

### PR DESCRIPTION
**Pull request by pftom**
Close #67 

* Use flying-wing layout make content center
* Move catalogue to the left
* Ensure content and catalogue don't change width when browser size is changing

### CODE REVIEW

**Comment by mRcfps** [comment]
Here is what catalogue looks like on my machine:

image

**Comment by pftom** [comment]
It seems we need handle this scroll bug as soon as possibile.

**Comment by pftom** [comment]
Maybe it's browser difference, can you fix it ? And still can show scroll bar when content is overflow the container height. Thanks!

**Comment by pftom** [comment]
@mRcfps @tomwenthey I was pushed a commit for fix scrollbar problem, can you review it for me?

**Pull request merged**
